export class Vet {
    constructor(idVet,name,email,password,createDate){
        this.idVet = idVet,
        this.name = name,
        this.displayName = name,
        this.names = "",
        this.lastName1 = "",
        this.lastName2 = "",
        this.title = "",
        this.federalProffessionNumber = "",
        this.federalTaxId = "",
        this.createDate = createDate,
        this.publicPhone1 = "",
        this.publicPhone2 = "",
        this.whatsAppNum1 = "",
        this.whatsAppNum2 = "",
        this.email = email,
        this.img_src = "",
        this.password = password,
        this.registryComplete = "N",
        this.public_email1 = "",
        this.public_email2 = "",
        this.lastValidationDate = "",
        this.validationResult = "",
        this.nextValidationDate = "",
        this.status = 'P',
        this.municipality = "",
        this.city = "",
        this.county = "",
        this.state = "",
        this.state_desc = "",
        this.country = "MEX",
        this.country_desc = "México",
        this.zipcode = "",
        this.maps = "",
        this.address = [],
        this.specialties = [],
        this.education = [],
        this.price_rates = [],
        this.availability = {
            "monday":[],
            "tuesday":[],
            "wednesday":[],
            "thursday":[],
            "friday":[],
            "saturday":[],
            "sunday":[]
        },
        this.billing = 0,
        this.billing_name = ""
    }
}